### PR TITLE
Linked data

### PR DESCRIPTION
**Pull request by OneFishTwoFishRedFish-JFish**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

Pages with data that have a foreign key can't display the related data

## What is the new behavior?

There's a new Attribute Type so that you can define the foreign key related data and display in a dropdown.

## Additional context

Is this what you had in mind for Issue #18 ? 
I can think of other features to add like including an option query parameter for defining other constraints.
Also, please note the naming - I'm open to changing any of it.

### CODE REVIEW

**Comment by OneFishTwoFishRedFish-JFish** [comment]
I didn't include an example in the commit, but this is what a page with the linked data looks like in the dashibaseConfig
`    {
      name: "Team",
      page_id: "team",
      table_id: "Team",
      id_col: "TeamId",
      //user_col: "Owner",
      enforce_user_col: false,
      mode: "list",
      attributes: [
        {
          id: "Name",
          label: "Name",
          required: false,
          readonly: false,
          type: AttributeType.Text,
          //enumOptions: ['foo', 'bar'], // Specify enum options
        } as Attribute,
        {
          id: "LeagueId",
          label: "League",
          required: false,
          readonly: false,
          type: AttributeType.PageX,
          linkedPage: {
            name: 'league',
            id_col: 'LeagueId',
            value_col: 'Name',
          } as LinkedPage
        } as Attribute,
      ]
    },`

**Comment by greentfrapp** [comment]
Wow nice! Thanks @OneFishTwoFishRedFish-JFish - I might take a while to review this because I'm working on a related issue as well. Will get back to you by Friday night, please bump this thread if I don't.

But in the meantime, I'll absolutely love to set up some time to chat - if you're up for a call, could you send an email to sk@dashibase.com?

**Comment by OneFishTwoFishRedFish-JFish** [comment]
cool! we've got a meeting set up at 9:30am CST tomorrow :)

**Comment by greentfrapp** [comment]
Ah that's you! Got it - see you then!

**Comment by OneFishTwoFishRedFish-JFish** [comment]
Would like to close this PR, the latest JOIN commit accomplishes this plus a whole lot more.

**Pull request closed without merging**
